### ISSUE TITLE
Update button needs a fix for game list

### ISSUE THREAD

**Issue by Lectric1** [jonzenor/ChristianGuilds#155] opened 2020-08-23 12:42 UTC
![image](https://user-images.githubusercontent.com/54757398/90978530-a3501180-e51c-11ea-96f4-9d835128309d.png)

**Comment by jonzenor** [comment] 2020-08-24 15:44
Duplicate of #160, or it was a duplicate of this one? Either way, closing.

**Closed as completed by jonzenor** 2020-08-24 15:44 UTC
Labels: duplicate, language
